version: "3.9"

services:

  # =========================
  # 🚀 SPRING BOOT BACKEND
  # =========================
  backend:
    image: yezawhlaing/zkar:latest   # use docker hub image
    container_name: video_backend
    restart: always

    ports:
      - "8080:8080"

    env_file:
      - .env
#
#    environment:
#      SPRING_DATASOURCE_URL: ${DB_URL}
#      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
#      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
#      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQL8Dialect